version: '3.8'

services:
  elasticmq:
    container_name: scala-consumer-elasticmq
    image: softwaremill/elasticmq-native:1.3.14
    ports:
      - 9324:9324
      - 9325:9325

  mysql:
    container_name: scala-consumer-mysql
    image: mysql:8.0-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scala
      MYSQL_PASSWORD: scala
      MYSQL_DATABASE: scala
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql_mode="STRICT_TRANS_TABLES"

  mysql-admin:
    container_name: scala-consumer-mysql-admin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    depends_on:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: root
